import { GetApiKeyPopup } from "@/components/Home/Tool/GetApiKeyPopup";
import { Button, Container, Text, useDisclosure } from "@chakra-ui/react";
import Head from "next/head";
import { PropsWithChildren } from "react";

export const DefaultLayout = ({ children }: PropsWithChildren) => {
  const getApiKeyPopup = useDisclosure();

  return (
    <>
      <Head>
        <title>chatGPT Makers</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css2?family=Rajdhani:wght@300;400;500;600;700&display=swap"
          rel="stylesheet"
        />
      </Head>
      <Container maxWidth="100%">
        <Text fontSize="6xl">chatGPT Makers</Text>
        <Button margin="-20px 0 20px 0" onClick={getApiKeyPopup.onOpen}>
          API KEY Nasıl Alınır?
        </Button>

        {children}
      </Container>

      <GetApiKeyPopup {...getApiKeyPopup} />
    </>
  );
};
